### PR TITLE
Added error handling for socket and channel connect.

### PR DESCRIPTION
**Pull request by conor-mac-aoidh**
As discussed in [this issue](https://github.com/vic/apollo-phoenix-websocket/issues/1)

### CODE REVIEW

**Comment by vic** [comment]
Thanks, I'm adding a test for this and will merge.

**Comment by vic** [comment]
Btw @conor-mac-aoidh is sending `leave` required?

**Comment by vic** [comment]
@conor-mac-aoidh  could you review the changes?

I added a couple of tests, and did the following, is that ok?

1) Make sure we also reject if its not possible to join the channel
2) Dont wrap the response on Error, reject with it and let the user handle it if needed

**Comment by conor-mac-aoidh** [comment]
Thanks for the commits @vic 

I have just done some testing and I don't think sending leave is required.

However, the reason for wrapping responses in an Error is for error handling. Without this, the error is thrown from `apollo.watchQuery` as follows:

```
Error: Network error: undefined
    at new ApolloError (http://localhost:4200/vendor.bundle.js:55349:23) [angular]
    at http://localhost:4200/vendor.bundle.js:54809:39 [angular]
```

But when this is wrapped in Error, the error message is passed through as:

```
Error: Network error: Unauthorized
    at new ApolloError (http://localhost:4200/vendor.bundle.js:55349:23) [angular]
    at http://localhost:4200/vendor.bundle.js:54809:39 [angular]
```

So, without wrapping in Error, it is not possible to handle different types of errors afaik. Or maybe this is something that can be handled by afterware? I will try that also now.

**Comment by vic** [comment]
Regarding `leave` if you confirm it's not required when actually interacting with a phoenix backend, could you remove it in another PR? :)

Btw, just added you as contributor, thank you for all your work. ❤️

**Comment by conor-mac-aoidh** [comment]
Thanks for adding me as a contributor! And no problem, thanks for creating the repo, it made my task a lot easier!

I will work on a PR for that this afternoon

**Pull request merged**
